[tool.black]
line-length = 100
target-version = ["py312"]
include = "\\.pyi?$"
extend-exclude = "(\\.venv|build|dist|artifacts|data)(/|\\\\)"

[tool.isort]
profile = "black"
line_length = 100
src_paths = ["src", "tests"]
skip = [".venv", "build", "dist", "artifacts", "data"]