
// IL2CPP Hook Script for com.example.app
// Generated by APK Analyzer Tool

console.log("[+] IL2CPP Hook Script loaded for com.example.app");

Java.perform(function() {
    console.log("[+] Java.perform started");
    
    // IL2CPP関数のフック
    
    
    // IL2CPPドメイン情報の取得
    var il2cpp_domain_get_ptr = Module.findExportByName("libil2cpp.so", "il2cpp_domain_get");
    if (il2cpp_domain_get_ptr) {
        Interceptor.attach(il2cpp_domain_get_ptr, {
            onEnter: function(args) {
                console.log("[+] il2cpp_domain_get called");
            },
            onLeave: function(retval) {
                console.log("[+] Domain: " + retval);
            }
        });
    }
    
    // メモリ割り当ての監視
    var malloc_ptr = Module.findExportByName("libc.so", "malloc");
    if (malloc_ptr) {
        Interceptor.attach(malloc_ptr, {
            onEnter: function(args) {
                this.size = args[0].toInt32();
            },
            onLeave: function(retval) {
                if (this.size > 1024 * 1024) { // 1MB以上の割り当てをログ
                    console.log("[MEMORY] Large allocation: " + this.size + " bytes at " + retval);
                }
            }
        });
    }
});

console.log("[+] IL2CPP Hook Script setup complete");
