name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.10"}
      - shell: pwsh
        run: python -m pip install -U pip wheel
      - shell: pwsh
        run: python -m pip install -r requirements.txt 2>$null; if ($LASTEXITCODE -ne 0) { Write-Host "no reqs" }
      - shell: pwsh
        run: python -m pip install black isort pytest pytest-cov mypy pre-commit cyclonedx-bom
      - shell: pwsh
        run: black --check .
      - shell: pwsh
        run: isort --check-only .
      - shell: pwsh
        run: mypy --strict src
      - shell: pwsh
        run: |
          if (-not (Test-Path "observability/coverage")) { New-Item -ItemType Directory -Force "observability/coverage" | Out-Null }
          pytest -q --maxfail=1 --strict-markers -m "not integration and not e2e and not slow" --cov=src --cov-report=xml:observability/coverage/coverage.xml
      - name: SFT Intake Smoke Test
        shell: pwsh
        run: |
          python -X utf8 tools/intake_filter.py --data-dir tests/fixtures/intake --expect-errors 2 --expect-accepted 2
      - name: Pre-commit (advisory)
        shell: pwsh
        continue-on-error: true
        run: pre-commit run -a
      - name: SBOM (best-effort)
        shell: pwsh
        continue-on-error: true
        run: |
          if (-not (Test-Path "observability/sbom")) { New-Item -ItemType Directory -Force "observability/sbom" | Out-Null }
          cyclonedx-bom -o observability/sbom/sbom.json
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: observability/coverage/coverage.xml
