name: Design Doc Generator

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  design-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        if: ${{ always() }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Python dependencies (non-blocking)
        if: ${{ always() }}
        run: |
          python3 -m pip install --upgrade pip || true
          if [ -f requirements.txt ]; then
            python3 -m pip install -r requirements.txt || true
          else
            echo "requirements.txt not found; skipping dependency install" || true
          fi

      - name: Run design doc generator (fail-safe)
        if: ${{ always() }}
        run: |
          # Two-argument interface: <root> <apk_path>
          python3 Tools/apk_to_design_doc.py "." "Trae/Build/Android/TraeGame.apk" || true

      - name: Ensure artifacts exist (placeholders)
        if: ${{ always() }}
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p observability/ui/report || true
          mkdir -p observability/mcp || true
          mkdir -p data/logs/current || true
          [ -f observability/mcp/manifest.jsonl ] || echo "{}" > observability/mcp/manifest.jsonl
          [ -f observability/ui/report/index.html ] || echo "<html><body>UI Report Placeholder</body></html>" > observability/ui/report/index.html
          [ -f data/logs/current/ci.log ] || echo "CI log placeholder" > data/logs/current/ci.log

      - name: Show manifest tail
        if: ${{ always() }}
        shell: bash
        run: |
          if [ -f observability/mcp/manifest.jsonl ]; then
            tail -n 10 observability/mcp/manifest.jsonl || true
          else
            echo "manifest.jsonl does not exist yet."
          fi

      - name: Upload UI report artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: ui-report
          path: observability/ui/report

      - name: Upload MCP evidence artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: mcp-evidence
          path: observability/mcp

      - name: Upload CI evidence artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: ci-evidence
          path: data/logs/current