name: pre-commit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install pre-commit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run pre-commit (all files)
        run: pre-commit run --show-diff-on-failure --color=always --all-files

      - name: Run pre-commit (pre-push stage)
        run: pre-commit run --show-diff-on-failure --color=always --all-files --hook-stage pre-push
