repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        name: mypy (selected files)
        args: ["--show-error-codes", "--pretty"]
        additional_dependencies: ["types-requests"]
        stages: [pre-push]
        files: ^src/

  - repo: local
    hooks:
      - id: pytest-smoke
        name: pytest smoke
        entry: python -m pytest -q tests/test_localai_smoke.py
        language: system
        pass_filenames: false
        stages: [pre-push]
