# .github/workflows/pre-commit.yml
name: ci
on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python -m pip install -U pip
      - run: pip install -r requirements.txt || true
      - run: pip install black==25.1.0 isort==6.0.1 mypy==1.11.2 pytest types-requests
      - name: Black (check)
        run: black --check .
      - name: Isort (check)
        run: isort --check-only .
      - name: Mypy
        run: mypy src
      - name: Pytest smoke
        run: pytest -q tests/test_localai_smoke.py
